[package]
name = "safe-migrate"
version = "0.4.4"
edition = "2024"
rust-version = "1.85"
description = "Analyze PostgreSQL migrations for schema and locking risks"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dsecurity49/safe-migrate"
readme = "README.md"
exclude = ["live_tests/.safe-migrate.cache"]
keywords = ["postgres", "migration", "linter", "ast", "database"]
categories = ["command-line-utilities", "database"]

[dependencies]
squawk-syntax = "=2.61.0"
squawk-lexer  = "=2.61.0"
squawk-parser = "=2.61.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
thiserror = "1.0"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
postgres = "0.19"
rowan = "0.15.18"
owo-colors = "4"
terminal_size = "0.3"
comfy-table = "7"
bincode = { package = "bincode-next", version = "2.1", features = ["serde"] }
zstd = "0.13"
crossterm = "0.27.0"
tempfile = "3.10"
chacha20poly1305 = { version = "0.11", features = ["getrandom"] }

[dev-dependencies]
assert_cmd = "2.0"
postgres = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
