CREATE TABLE parent (a integer, b integer) PARTITION BY RANGE (a, b);
CREATE TABLE child PARTITION OF parent FOR VALUES FROM (0, 0) TO (10, 10);
ALTER TABLE parent DETACH PARTITION child CONCURRENTLY;
