CREATE TABLE parent (a integer, b integer, c integer) PARTITION BY RANGE (a, b, c);
CREATE TABLE child PARTITION OF parent FOR VALUES FROM (1, MINVALUE, MINVALUE) TO (10, MAXVALUE, MAXVALUE);
ALTER TABLE parent DETACH PARTITION child CONCURRENTLY;