CREATE TABLE parent (a integer, b integer) PARTITION BY RANGE (a, b);
CREATE TABLE child PARTITION OF parent FOR VALUES FROM (MINVALUE, MINVALUE) TO (MAXVALUE, MAXVALUE);
ALTER TABLE parent DETACH PARTITION child CONCURRENTLY;